//
// Created by TLKG-014 on 2020/11/16.
//

#ifndef WUKONG_DEMO_LOWVERSION_GLCOMMON_H
#define WUKONG_DEMO_LOWVERSION_GLCOMMON_H

enum YUVTYPE{
    IMAGE_FORMAT_NV12,
    IMAGE_FORMAT_NV21,
    IMAGE_FORMAT_I420

};

#endif //WUKONG_DEMO_LOWVERSION_GLCOMMON_H
