/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "SoFindCard.h"
/* Header for class com_example_findcard_FindcardTest */

#ifndef _Included_com_example_findcard_FindcardTest
#define _Included_com_example_findcard_FindcardTest
#ifdef __cplusplus
extern "C" {
#endif

SoFindCard soFindCard;
    /*
 * Class:     com_example_findcard_FindcardTest
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_findcard_FindcardTest_init
  (JNIEnv * env, jobject obj){
    soFindCard.init();
}

/*
 * Class:     com_example_findcard_FindcardTest
 * Method:    loopgetcard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_findcard_FindcardTest_loopgetcard
  (JNIEnv * env, jobject obj){
    soFindCard.start();
    soFindCard.start();
}

/*
 * Class:     com_example_findcard_FindcardTest
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_findcard_FindcardTest_stop
  (JNIEnv * env, jobject obj){
    soFindCard.stop();
}

#ifdef __cplusplus
}
#endif
#endif
