/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <timer/wktimer.h>
/* Header for class com_example_timer_TimerBlock */

#ifndef _Included_com_example_timer_TimerBlock
#define _Included_com_example_timer_TimerBlock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_timer_TimerBlock
 * Method:    blockTimer
 * Signature: (I)V
 */
wktimer wtimer;
JNIEXPORT void JNICALL Java_com_example_timer_TimerBlock_blockTimer
  (JNIEnv *, jobject,jint maxtime){
    wtimer.block(maxtime);

}

#ifdef __cplusplus
}
#endif
#endif
